### ISSUE TITLE
Error display when installing the package

### ISSUE THREAD

**Issue by kennethtomagan** [jsdecena/baserepo#10]
The package successfully installed but there was an error display in the command line. 
I'm using fresh Laravel 6.0
```
In BaseRepository.php line 43:

  Argument 1 passed to Jsdecena\Baserepo\BaseRepository::__construct() must b
  e an instance of Illuminate\Database\Eloquent\Model, instance of Illuminate
  \Foundation\Application given, called in /home/kenneth/Sites/test1/vendor/l
  aravel/framework/src/Illuminate/Foundation/ProviderRepository.php on line 2
  08


```

**Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1**

**Comment by cgmalaquias** [comment]
@kennethtomagan , this issue is already open at #9

**Comment by jsdecena** [comment]
@kennethtomagan Can you try to do compose update now? 

in your terminal: `composer update jsdecena/baserepo`

**Comment by kennethtomagan** [comment]
@jsdecena  It's working now. Thanks!
