### ISSUE TITLE
Issue with base repository

### ISSUE THREAD

**Issue by qodeanil** [jsdecena/baserepo#11]
Hi everyone, I am getting this error after I updated the composer. can you please let me know what the issue is

In BaseRepository.php line 43:
                                                                               
  Argument 1 passed to Jsdecena\Baserepo\BaseRepository::__construct() must b  
  e an instance of Illuminate\Database\Eloquent\Model, instance of Illuminate  
  \Foundation\Application given, called in /vendor/laravel/framework/src/Illuminate/Foundation/Provid  
  erRepository.php on line 208  

Hope to get solution

**Comment by cgmalaquias** [comment]
@qodeanil , this issue is already open at #9

**Comment by jsdecena** [comment]
@qodeanil Can you try to do compose update now? 

in your terminal: `composer update jsdecena/baserepo`
