### ISSUE TITLE
Paginate array data return key value

### ISSUE THREAD

**Issue by edwinwongnetccentric** [jsdecena/baserepo#2]
the paginateArrayResults() return the data with key because of array_slice(). kindly wrap around array_values(). end result like this...

`array_values(array_slice($data, $offset, $perPage, true))`

I cant make a pull request (permission deneid).

**Comment by jsdecena** [comment]
Hi, can you try to make a PR now? I have changed some settings. I am just curious, are you affiliated w Ming of Netccentric SG?

**Comment by edwinwongnetccentric** [comment]
Yup, I work for this company. This is my work email. Alright, will try now.

**Comment by jsdecena** [comment]
cool. I am with Netccentric before :)

**Comment by edwinwongnetccentric** [comment]
Wow~ really?! The world is getting small XD. Anyway, I created a pull request :)

**Comment by jsdecena** [comment]
Merged! Also to Huiwen Yang, say hi from Me! :)

**Comment by edwinwongnetccentric** [comment]
Haha! cool! Iam from Malaysia branch :) I have no idea who is Huiwen Yang XD

**Comment by edwinwongnetccentric** [comment]
@jsdecena one last thing~ can update the php packagist? Thanks you!

**Comment by jsdmultisys** [comment]
@edwinwongnetccentric Which one? You mean the minimum version of php in `composer.json` file?

**Comment by edwinwongnetccentric** [comment]
Nope~ the composer package version. here https://packagist.org/packages/jsdecena/baserepo. now the latest is version 1.0.3, it should be 1.0.4
