### ISSUE TITLE
Pagination with getData method doesn't parse the include transformer

### ISSUE THREAD

**Issue by Neticx** [jsdecena/baserepo#20]
Hi Jeff, im trying to use this package for my project, but problem comes when i need pagination feature for each of my API. when i trying to find on documentation. it doesn't exist. but when i look into the code, i found some method that can generated the pagination and meta cursor automatically. the method i use for it are `getData()`
i parse my query builder and transformer on that method. it works as well, but when i parse include param url on my api. it doesn't parse the include data. i figuring out what happened, and i know that in `getData()` method there is no code which execute the `parseIncludes()` method. so i add some line of code to fix this.
`if (isset($_GET['include'])) {
            $manager->parseIncludes($_GET['include']);
        }`

i know it's not good to change the code inside vendor folder because it will be removed if someone join in my project. so is there any proper way to doing pagination also parsing the include data in my transformer? with my pleasure i will make a PR and adding pagination documentation if not yet implemented on this package.
thanks for make this package

**Comment by jsdecena** [comment]
@Neticx you can do a PR so everyone can benefit from it : )

**Comment by jsdecena** [comment]
@Neticx is there any PR in the works? Will close this for now, let's reopen when there is a movement,
