### ISSUE TITLE
UsersTableSeeder from test folder is launched

### ISSUE THREAD

**Issue by goodmartian** [jsdecena/baserepo#23]
- Laravel Framework 8.42.1

### Description
When I run the artisan db:seed command also with my seeders, the UsersTableSeeder starts. Although I don't call him anywhere

![](https://i.imgur.com/jeDZ55a.png)

**Comment by jsdecena** [comment]
> * Laravel Framework 8.42.1
> 
> ### Description
> When I run the artisan db:seed command also with my seeders, the UsersTableSeeder starts. Although I don't call him anywhere
> 
> ![](https://camo.githubusercontent.com/939d18f974c9f22811a677752a37044e934559adfece846bfaadc538fefe2a36/68747470733a2f2f692e696d6775722e636f6d2f6a65445a3535612e706e67)

I see what you mean, have the check in the databaseSeeder class only run if env == testing

**Comment by jsdecena** [comment]
@goodmartian check this https://github.com/jsdecena/baserepo/commit/5d8e0ffd474d8e98f773a2d65f6aa104c8aec5d1
