### ISSUE TITLE
Wrong Instance Type

### ISSUE THREAD

**Issue by CraftLogan** [jsdecena/baserepo#5]
I keep getting this error when trying to install the package via composer.  

In BaseRepository.php line 43:
                                                                               
  Argument 1 passed to Jsdecena\Baserepo\BaseRepository::__construct() must b  
  e an instance of Illuminate\Database\Eloquent\ModelModel, instance of Illum  
  inate\Foundation\Application given, called in /Applications/MAMP/htdocs/dai  
  lyeatz/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepositor  
  y.php on line 208

**Comment by jsdmultisys** [comment]
@CraftLogan That means, you need to pass your model in the `parent::__construct($YourModel)` when extending this baserepo.

**Comment by saikumar-carbanio** [comment]
@jsdmultisys I'm still facing the same issue.
In the previous version I was not facing any issue, when I tried running the command 'composer update' I am getting this issue.

I have also tried your solution but nothing worked, can you please suggest us with few more solutions? 

Argument 1 passed to Jsdecena\Baserepo\BaseRepository::__construct() must be an instance of Illuminate\Database\Eloquent\Model, instance of Illuminate\Foundation\Application given, called in /var/www/html/carbanio/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php on line 208
