### ISSUE TITLE
Eloquent relations

### ISSUE THREAD

**Issue by Daniyal-Javani** [jsdecena/baserepo#6]
Is there anyway to use Eloquent relations with this project?

I've checked your code in Laracom project and I found this:
```
$order = $this->orderRepo->findOrderById($orderId);
$order->courier = $this->courierRepo->findCourierById($order->courier_id);
$order->address = $this->addressRepo->findAddressById($order->address_id);
```
https://github.com/Laracommerce/laracom/blob/6e5e147db363722be2e277f339e39cf5324a9101/app/Http/Controllers/Admin/Orders/OrderController.php#L120

Would you please tell me what's the point of not using Eloquent relations in the Repository design pattern? 

BR

**Comment by jsdecena** [comment]
@Daniyal-Javani I think it was done in a rush but it is always helpful to use the Eloquent's relationship. If I would rewrite it, I would:

```
$orderRepo = new OrderRepository($order);
$orderRepo->getCouriers(); // get the $order->couriers relation
$orderRepo->getAddress(); // get the associated address $order->address
```

You can create a PR though :)

**Comment by Daniyal-Javani** [comment]
Great! and what about one more PR to this project and add eager loading then use it like this?
```
$orderRepo = new OrderRepository($order);

$orderRepo = $orderRepo->with(['couriers', 'address']);

$orderRepo->getCouriers(); // get the $order->couriers relation
$orderRepo->getAddress(); // get the associated address $order->address
```
I know there is almost no performance improvement for this code but in somewhere else it may cause some.

**Comment by jsdecena** [comment]
You can do that as well. :)
