### ISSUE TITLE
Wrong Instance Type After Composer Update

### ISSUE THREAD

**Issue by saikumar-carbanio** [jsdecena/baserepo#9]
In the previous version I was not facing any issue, when I tried running the command 'composer update' I am getting this issue.

I have also tried your solution but nothing worked, can you please suggest us with few more solutions?

Argument 1 passed to Jsdecena\Baserepo\BaseRepository::__construct() must be an instance of Illuminate\Database\Eloquent\Model, instance of Illuminate\Foundation\Application given, called in /var/www/html/carbanio/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php on line 208

**Comment by cgmalaquias** [comment]
I have the same problem:

In BaseRepository.php line 43:
                                                                               
  Argument 1 passed to Jsdecena\Baserepo\BaseRepository::__construct() must b  
  e an instance of Illuminate\Database\Eloquent\Model, instance of Illuminate  
  \Foundation\Application given, called in /home/dev1/sites/ls-ecommerce/vend  
  or/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php on li  
  ne 208

**Comment by arowolojoshuao** [comment]
I also encountered the same problem and yet to be fixed:

In BaseRepository.php line 43:

Argument 1 passed to Jsdecena\Baserepo\BaseRepository::__construct() must b
e an instance of Illuminate\Database\Eloquent\Model, instance of Illuminate
\Foundation\Application given, called in /home/dev1/sites/ls-ecommerce/vend
or/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php on li
ne 208

**Comment by jsdecena** [comment]
I am looking into it guys. :)

**Comment by arslanramay** [comment]
I am also facing the same issue guys. @jsdecena please help us :) Thanks in advance!

**Comment by arslanramay** [comment]
Hi everyone, there is one temporary fix which worked for me. Just downgrade the package version to exactly **"1.0"** instead of using latest version i.e **1.0.6** or **"^1.0"**

`"jsdecena/baserepo": "1.0",`
`"jsdecena/mcpro": "1.1",`

**Comment by cgmalaquias** [comment]
> Hi everyone, there is one temporary fix which worked for me. Just downgrade the package version to exactly **"1.0"** instead of using latest version i.e **1.0.6** or **"^1.0"**
> 
> `"jsdecena/baserepo": "1.0",`
> `"jsdecena/mcpro": "1.1",`

To me, work:
- In config/app.php:
-- Remove line where package is informed
- Type on terminal: "php artisan cache:clear"
- remove the composer.lock
- remove folder vendor/
- install the packages: type "composer install"

But, the package need to be set in:
"jsdecena/baserepo": "1.0",
"jsdecena/mcpro": "1.1",

Need fix the update from package
Done.

**Comment by jsdecena** [comment]
@saikumar-carbanio @cgmalaquias @arowolojoshuao @arslanramay Can you try to do compose update now? 

in your terminal: `composer update jsdecena/baserepo`

**Comment by cgmalaquias** [comment]
Thanks @jsdecena. Works Here.
